### ISSUE TITLE
Could you upload the file "vtpm_proxy.h" in the project?

### ISSUE THREAD

**Issue by haiwei08** [stefanberger/linux-vtpm-tests#1]
The Project does not include the vtpm_proxy.h file, and cannot complie success.
Could you upload the file "vtpm_proxy.h" in the project?

**Comment by stefanberger** [comment]
`vtpm_proxy.h` is a Linux kernel header file. It becomes available when one installs the header files of a recent linux kernel either by installing the package that contains the linux header files (check your distro) or when one has the Linux sources on a system one can install them using the following command:

```
make headers_install ARCH=x86_64 INSTALL_HDR_PATH=/usr
```

I take this from this link here: https://www.kernel.org/doc/Documentation/kbuild/headers_install.txt

If this solves your problem, please close the issue.

**Comment by haiwei08** [comment]
Hi,Dear Stefan Berger:
I cannot find the vtpm_proxy.h in the linux kernel headers Project, but in the swtpm project .
I copy the vtpm_proxy.h file to the /usr/include/linux ,and it work, Thanks all the same.

**Comment by stefanberger** [comment]
It's been part of the Linux kernel since Linux 4.8: https://elixir.bootlin.com/linux/v4.8.17/source/include/uapi/linux/vtpm_proxy.h
